FROM --platform=${BUILDPLATFORM} alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG BUILD_DATE
ARG REVISION
ARG VERSION

RUN apk add --no-cache git && git --version

CMD ["sleep", "infinity"]

LABEL org.opencontainers.image.created=$BUILD_DATE \
    org.opencontainers.image.authors="Bruno Paz" \
    org.opencontainers.image.description="{{ project_description }}" \
    org.opencontainers.image.url="{{ project_url }}" \
    org.opencontainers.image.revision=$REVISION \
    org.opencontainers.image.version=$VERSION
