FROM --platform=${BUILDPLATFORM} alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG BUILD_DATE
ARG REVISION
ARG VERSION

RUN apk add --no-cache git && git --version

CMD ["sleep", "infinity"]

LABEL org.opencontainers.image.created=$BUILD_DATE \
    org.opencontainers.image.authors="Bruno Paz" \
    org.opencontainers.image.description="{{ project_description }}" \
    org.opencontainers.image.url="{{ project_url }}" \
    org.opencontainers.image.revision=$REVISION \
    org.opencontainers.image.version=$VERSION
